### PR TITLE
Fix: discuss.layer.io link made specific to the card

### LINKED ISSUE #69: discuss.layer.io link is not specific to the card
#### Current Behavior

When clicked outside the card, the discuss.layer5.io link gets activated - which should not be the case.

#### Expected Behavior

The link should only be activated when clicked on the card not beyond that.

#### Screenshots/Logs

https://user-images.githubusercontent.com/116095538/220164429-5b1cd64c-7bcd-4e99-a364-9c84ecdafcbe.mp4

#### Environment

- **Host OS:** Linux
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by swagataroy30**
**Notes for Reviewers**

This PR fixes #69 

## Before

https://user-images.githubusercontent.com/116095538/221918433-5d2b1c93-67be-4aa5-b5e2-19284f97d2d5.mp4

## After

https://user-images.githubusercontent.com/116095538/221918504-4dec541b-872a-4c0f-b9f3-aef646c0739c.mp4

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@BabyElias, would you like to offer review?

**Comment by BabyElias** [comment]
@leecalcote Yes, I would love to !

**Review by BabyElias — APPROVED** [review]
LGTM

**Review by leecalcote — APPROVED** [review]
Good stuff. Thank you, @swagataroy30

**Pull request merged**
