### PR TITLE
Feature/malaviya parth/138

### LINKED ISSUE #138: Changing to new Twitter X Logo
#### Current Behavior
image

#### Desired Behavior
image

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

### PR DESCRIPTION
**Pull request by malaviya-parth**
**Notes for Reviewers**

This PR fixes #138
1. Changes the Twitter logo to new Twitter X logo
2.  Also has the Custom Scroll-Bar code

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by malaviya-parth** [comment]
Well Again as Preview failed here are the attached screenshots of the output:
**Normal**
image
**On Hover**
image

**Review by thisiskaransgit — CHANGES_REQUESTED** [review]
Thanks @malaviya-parth, please use svg, see the recent  implementation on meshery.io https://github.com/meshery/meshery.io/pull/1342/

**Review by thisiskaransgit — CHANGES_REQUESTED** [review]
@malaviya-parth, the logo is not distinguishable on hover, please invert the colors, so that outlines are white when highlighted

**Comment by Ghat0tkach** [comment]
Hey @malaviya-parth 
Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Pull request closed without merging**
