### PR TITLE
fix: fixes footer and other links for Slack

### LINKED ISSUE #41: fix: fix Slack links in the footer
#### Current Behavior

The Slack links (under Community and Socials section) in the footer take to 404 page and Service Mesh Interface page respectively.

#### Expected Behavior

The links should direct to the official Slack of Meshery.

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

@leecalcote I'd like to work on this issue. Kindly assign.

### PR DESCRIPTION
**Pull request by abhilipsasahoo03**
**Notes for Reviewers**

This PR fixes #41

# Description
- Fixes links for Slack in the website.

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by abhilipsasahoo03** [comment]
@leecalcote kindly review!

**Review by UtkarshMishra12 — APPROVED** [review]
LGTM! Thanks @abhilipsasahoo03 😊🎉

**Comment by abhilipsasahoo03** [comment]
> LGTM! Thanks @abhilipsasahoo03 😊🎉

If all's good, kindly merge? :)

**Comment by UtkarshMishra12** [comment]
@leecalcote @Chadha93 Please merge this PR

**Pull request merged**
