### PR TITLE
Adding login button

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: leecalcote <leecalcote@gmail.com>

**Notes for Reviewers**

This PR adds a login button and restyles each nav button.

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@lolverae, you might like to review this PR.

**Comment by Nikhil-Ladha** [comment]
The buttons are not responsive, and the shadow could be reduced a bit I think.

**Comment by leecalcote** [comment]
> The buttons are not responsive, and the shadow could be reduced a bit I think.

Excellent feedback, @Nikhil-Ladha. I have attempted to incorporate each point. 👍

**Comment by leecalcote** [comment]
A healthy number of users have been granted access to the playground and will need to see the playground.meshery.io link now, so I'm merging to ensure they aren't missing it. Please do enhance if I missed something.

**Comment by Nikhil-Ladha** [comment]
> A healthy number of users have been granted access to the playground and will need to see the playground.meshery.io link now, so I'm merging to ensure they aren't missing it. Please do enhance if I missed something.

Looks good, which makes it difficult to believe that the person behind this PR is Mr. Lee himself 🤣

**Pull request merged**
