### PR TITLE
Mobile responsive navbar

### LINKED ISSUE #64: [Site] Update navbar for mobile screens
#### Current Behavior

Currently the navbar remains same throughout all screen sizes and looks a bit cramped for smaller screens.
dark-old

#### Desired Behavior
For screens  below 500px the navbar will have a sort of hamburger menu.

dark-new-open

#### Implementation
I was thinking about moving the entire navbar into its own navigation component. While the theme state will remain in app.js we can use props to pass and change its value from inside navigation component. If there is any other approach to this please let me know.

#### Mockups

light-new-nav
light-new-open

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

### PR DESCRIPTION
**Pull request by Avi-88**
This PR updates the navbar for smaller screens as proposed in the mentioned issue

This PR fixes #64 

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
@Avi-88 the deployment preview failed to build. Would you like to confirm that you're able to build locally? Please double-check on the failure reason.

**Comment by Avi-88** [comment]
> @Avi-88 the deployment preview failed to build. Would you like to confirm that you're able to build locally? Please double-check on the failure reason.

Hi @leecalcote , there was a unused component which caused the build to fail as netlify treats warnings as errors. The preview is successfully generated now , please let me know if you need any changes, thanks

**Comment by leecalcote** [comment]
@roopeshsn will you review and offer feedback?

**Comment by roopeshsn** [comment]
> @roopeshsn will you review and offer feedback?

Sure, I'll do that.

**Review by roopeshsn — COMMENTED** [review]
Looks good to me. The concern was the code formatting. Also, I am not sure it matters. Other than that all good. Good work @Avi-88!

**Comment by swagataroy30** [comment]
Hey just wanted to add my suggestions here - I don't think a separate mobile menu would be required as we don't have any navigation links we can keep things simple and also with the theme-toggler inside the mobile menu like that doesn't seem to stand out - people won't notice. I was thinking if we can keep it simple and do something like this. it's just a suggestion would really like to know all of your views on this.
Screenshot from 2023-02-21 00-44-31

**Comment by Avi-88** [comment]
> Looks good to me. The concern was the code formatting. Also, I am not sure it matters. Other than that all good. Good work @Avi-88!

Sorry for the delayed reply and thankyou for  the feedback @roopeshsn , I'll try and fix the formatting ASAP, I'm a little busy atm due to clg work

**Comment by Avi-88** [comment]
> Hey just wanted to add my suggestions here - I don't think a separate mobile menu would be required as we don't have any navigation links we can keep things simple and also with the theme-toggler inside the mobile menu like that doesn't seem to stand out - people won't notice. I was thinking if we can keep it simple and do something like this. it's just a suggestion would really like to know all of your views on this.
> Screenshot from 2023-02-21 00-44-31
> 

Hi @swagataroy30 , thank you for the suggestion. Although we currently do not have any other navigation within the page, that might not be the case in future. I'm not sure how large the scope of this site will be but it's better to prepare for it. Also about the  mode switch being inside menu, it's only made that way because as you said we currently don't have many links and it would look weird to have just 2 buttons in there. As far as it's use, I've seen plenty of similar implementations so i thought it wouldn't be that much of a problem. Still I'm open to hear other people's opinion on this, thanks

**Comment by leecalcote** [comment]
If we haven't reviewed this in the Websites meeting, perhaps, a quick review will get this over the hump.

**Comment by Avi-88** [comment]
> If we haven't reviewed this in the Websites meeting, perhaps, a quick review will get this over the hump.

Sorry about that @leecalcote , this one slipped my mind. There are multiple PR's from my end that have been completed but need a final review before merge , I'll update all of them and bring them up in the next meeting, thanks for the reminder

**Comment by leecalcote** [comment]
> > If we haven't reviewed this in the Websites meeting, perhaps, a quick review will get this over the hump.
> 
> Sorry about that @leecalcote , this one slipped my mind. There are multiple PR's from my end that have been completed but need a final review before merge , I'll update all of them and bring them up in the next meeting, thanks for the reminder

Thank you, @Avi-88. I'll see you on tomorrow's meeting.

**Review by leecalcote — APPROVED** [review]
LGTM

**Pull request merged**
