### PR TITLE
replace signup form with modal

### LINKED ISSUE #214: Remove the signup form
#### Current Behavior
we have signup form.

#### Expected Behavior
remove the signup form on https://play.meshery.io/

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by vishalvivekm**
**Notes for Reviewers**

This PR fixes #214 

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by vishalvivekm** [comment]
image

**Review by hargunkaur286 — COMMENTED** [review]
Screenshot 2024-10-18 at 3 01 51 PM

Just a few suggestions:

1. Since this page is about trying out the playground, wouldn't it be better if the modal opens on clicking the big button that comes on the screen, instead of keeping the "try it out" button on top right. I mean, when I opened up the page, my first intuition was that the playground would open when I click that button, but rather, it redirected me to slack.

2. Can we also keep this discussion forum box
Screenshot 2024-10-18 at 3 06 35 PM

3. The video preview image is not visible
Screenshot 2024-10-18 at 3 09 51 PM

4. White colour text on yellow background I think do not go well together. Instead, can we keep the text colour as "black"?
Screenshot 2024-10-18 at 3 12 14 PM

**Comment by vishalvivekm** [comment]
Thank you @hargunkaur286 
I'll address these.

**Comment by vishalvivekm** [comment]
@hargunkaur286 
"Join the community" and Discuss calll out: 
image

any suggestions?

**Comment by vishalvivekm** [comment]
fixed :-

> 2. Can we also keep this discussion forum box
> 3. The video preview image is not visible
> 4. White colour text on yellow background I think do not go well together. Instead, can we keep the text colour as "black"?

**Review by hargunkaur286 — APPROVED** [review]

**Review by sudhanshutech — APPROVED** [review]

**Pull request merged**
