### PR TITLE
Bug #155 TextAlign Center 

### LINKED ISSUE #155: [UX - Responsiveness] Learn - text alignment not consistent
### Current Behaviour

- Link to website: https://play.meshery.io/
- The paragraph text under "The Cloud Native Playground" is center aligned
- However the text under "Sign-up to receive a user account..." is left aligned, additionally, the subheading under "Frequently Asked Questions" is also left aligned.

#### Screenshots

su
fqa

### Suggested Behaviour
- To maintain design consistency text should have the same format i.e either left aligned or center aligned.

#### Screenshots

mp
su

### Environment:
- Host OS: Mobile responsiveness
- Browser:

---
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

### PR DESCRIPTION
**Pull request by ayusudi**
**Notes for Reviewers**

This PR fixes #155 

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by ayusudi** [comment]
The update
image
image

**Review by sandramsc — COMMENTED** [review]
LGTM

**Comment by sandramsc** [comment]
> Hello @sandramsc , I hope this message finds you well. I'm currently unsure about the next steps, and I wanted to reach out to you regarding the review stage. If you have any specific input or guidance, please let me know..
> 
> Additionally, if there are any further frontend tasks that I can assist with, I would be more than happy to do so. Thank you for your support 🚀

Hi @ayusudi , so great that you are motivated and eager to continue contributing! Generally, once a PR has been made contributors and maintainers alike take a look and submit a review either requesting changes or approving the PR. The time within which this happens varies as maintainers are usually very occupied, but do make it a priority to review PR's at their earliest convenience.

**Review by leecalcote — APPROVED** [review]
Thanks, @sandramsc! 

Thanks, @ayusudi! @ayusudi, here's an issue that needs help - https://github.com/meshery/meshery/issues/10254

**Pull request merged**
