### PR TITLE
Made Signup form responsive for smaller devices

### LINKED ISSUE #28: [Site] Form is not mobile responsive
#### Current Behavior
image

#### Expected Behavior
Make the form responsive across every breakpoint.

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by gogoiakash2311**
**Description**
Signed-off-by: AkashGogoi <gogoiakash09@gmail.com>

This PR fixes #28

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Good. Does this PR replace https://github.com/meshery/play/pull/31? Should https://github.com/meshery/play/pull/31 be closed?

**Comment by leecalcote** [comment]
@gogoiakash2311 follow these instructions to sign your commits - https://github.com/meshery/play/pull/34/checks?check_run_id=9715429720

**Comment by leecalcote** [comment]
@gogoiakash2311, follow these instructions to configure your system to allows sign your commits, so that you don't have to worry about it any more and so that maintainers don't have to remind you to do this each time. 😉  - - https://github.com/meshery/play/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin

**Comment by gogoiakash2311** [comment]
> Good. Does this PR replace #31? Should #31 be closed?

Yes #31 should be closed

**Comment by gogoiakash2311** [comment]
> @gogoiakash2311, follow these instructions to configure your system to allows sign your commits, so that you don't have to worry about it any more and so that maintainers don't have to remind you to do this each time. 😉 - - https://github.com/meshery/play/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin

I forgot to sign-off my commits. I'll follow the instructions

**Comment by leecalcote** [comment]
> > @gogoiakash2311, follow these instructions to configure your system to allows sign your commits, so that you don't have to worry about it any more and so that maintainers don't have to remind you to do this each time. 😉 - - https://github.com/meshery/play/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin
> 
> I forgot to sign-off my commits. I'll follow the instructions

Sounds great. No sweat. 👍

**Comment by gogoiakash2311** [comment]
Thanks, @leecalcote for the guidance. Done with the sign-off commits.

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
