### PR TITLE
sign up button disappears when successfully signed up

### LINKED ISSUE #105: After sign up issue
#### Current Behavior
After the user signs up, the sign up button still appears on the screen.

image

#### Expected Behavior
The button should disappear after successful signup.
 I would like to work on this issue.

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by HetviSoni**
**Notes for Reviewers**

This PR fixes #105
I have added a handleSignUpFormSubmit function in the parent component of Navigation and SignupForm (ie App) which handles the appearance/disappearance of the signup button in the header.

https://github.com/meshery/play/assets/76479104/2f9797a0-e1b4-4790-83cf-d54c4347296e

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by HetviSoni** [comment]
> @HetviSoni The change is working as intended, resolve the merge conflicts and we are good to go

Done

**Review by thisiskaransgit — APPROVED** [review]
Looks good to merge, thank you for your contribution :tada:

**Comment by leecalcote** [comment]
Uh-oh, we have a merge conflict, @HetviSoni. Will you address this, please?

@Savio629 will you give this a review, too?

**Comment by HetviSoni** [comment]
> Uh-oh, we have a merge conflict, @HetviSoni. Will you address this, please?
> 
> @Savio629 will you give this a review, too?

Resolved👍

**Review by Savio629 — COMMENTED** [review]
LGTM 👍

**Comment by leecalcote** [comment]
Uh-oh, a merge conflict has popped up

**Comment by HetviSoni** [comment]
> Uh-oh, a merge conflict has popped up

Resolved👍 :)

**Comment by HetviSoni** [comment]
This pr has been open for a while now. It would be helpful if is merged or if any other changes are required, please suggest

**Review by asubedy — APPROVED** [review]

**Pull request merged**
