### PR TITLE
[Grammar Adjustment] Learn - content next to the Get Early Access form

### LINKED ISSUE #151: [Grammar Adjustment] Learn - content next to the "Get Early Access" form
**Current State:**

- Link to website: https://play.meshery.io/
- Currently, the text reads as follows: "Sign-up to receive a user account, entitled with perpetually free and full access the Playground environment."

**Desired State:**

- The suggested change is to add the word _to_ so it reads: "Sign-up to receive a user account, entitled with perpetually free and full access to the Playground environment."

---
**Screenshot**
mesh

### PR DESCRIPTION
**Pull request by VivekBaldha0712**
**Notes for Reviewers**

This PR fixes #151

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by VivekBaldha0712** [comment]
Please review this PR @Mohith234

**Review by hirentimbadiya — CHANGES_REQUESTED** [review]
@VivekBaldha0712, everything good but can you revert the changes made by you in package-lock.json file ?

**Comment by saurabh100ni** [comment]
let's discuss this item on today's website meeting,
please add this agenda in the docs: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk

**Comment by VivekBaldha0712** [comment]
@leecalcote Please review this PR

**Review by leecalcote — APPROVED** [review]
Thank you!

**Pull request merged**
