### PR TITLE
Added Responsiveness to the form

### LINKED ISSUE #28: [Site] Form is not mobile responsive
#### Current Behavior
image

#### Expected Behavior
Make the form responsive across every breakpoint.

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by gogoiakash2311**
Signed-off-by: Akash <gogoiakash09@gmail.com>

**Description**

This PR fixes #28

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@thisiskaransgit I encourage you to review this PR.

**Comment by leecalcote** [comment]
Thank you for opening this, @gogoiakash2311 👍

**Comment by Nikhil-Ladha** [comment]
https://github.com/meshery/play/issues/28#issuecomment-1325969954

**Comment by Nikhil-Ladha** [comment]
@gogoiakash2311 unfortunately we will have to give priority to PR #29 since it was opened earlier. If we don't hear back from the contributor regarding the requested update then we will move forward with your PR.

This is the reason why you should always have the issue assigned to you before sending out a PR, not only at Layer5 but in general when you do any open-source contribution.

**Comment by gogoiakash2311** [comment]
Okay. but the issue was assigned to me at first. And also I'm working on it

**Comment by Nikhil-Ladha** [comment]
> Okay. but the issue was assigned to me at first. And also I'm working on it

Ahh, ok. I misread between the conversations and did not notice the assignee.
Sorry for the confusion, please go ahead with the PR.

**Comment by gogoiakash2311** [comment]
No worries. 😊

**Comment by gogoiakash2311** [comment]
Preview for the issue https://github.com/meshery/play/issues/28 at: https://melodic-gnome-e0499c.netlify.app/
@Nikhil-Ladha @leecalcote  Let me know if any changes are required.
After that, I'll make a new PR

**Comment by leecalcote** [comment]
A deploy preview has been added.

**Comment by gogoiakash2311** [comment]
Preview for the issue https://github.com/meshery/play/issues/28 at: https://glowing-brigadeiros-33f419.netlify.app/
@leecalcote @Nikhil-Ladha  Let me know if any changes are required.
After that, I'll make a new PR

**Pull request closed without merging**
