### PR TITLE
Added some transition effects to buttons on the home page

### LINKED ISSUE #73: Adding some basic transition effects to the various buttons on the home page.
#### Current Behavior
Right now we have some hover effects on buttons and all. But they don't have any transition effect which makes it look a little unpolished. Also the "Join our community button" still doesn't have the effect. 

#### Desired Behavior
- To add some basic transitioning to the buttons
- Add the same hover effect to the join community button

#### Implementation

- Some CSS rules need to be added.

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

### PR DESCRIPTION
**Pull request by sidtohan**
This is a follow up to the issue raised regarding lack of transition effects on buttons.
**Notes for Reviewers**

This PR fixes #73

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by sidtohan** [comment]
@leecalcote can you please have a look at his whenever possible? Thanks.

**Comment by Avi-88** [comment]
Hi @sidtohan , good job on the changes. Think of this as a add on to your changes, so I was thinking about adding a little box shadow on hover for the buttons, kinda like a glow effect as the current effects are not that prominent, do let me know what you think about that. If you have any other suggestion in mind please feel free to share it too, thanks

**Comment by sidtohan** [comment]
@Avi-88 that's a great idea. Other than that i don't think anything else is needed, it's best if the effects are subtle. 

I'll get to work on the box shadows. Thanks.

**Comment by sidtohan** [comment]
@Avi-88 I have done the required changes. If there are any further improvements that can be made, please kindly tell.
Thanks.

**Review by Avi-88 — APPROVED** [review]
LGTM , nice work @sidtohan

**Comment by sidtohan** [comment]
If it's all good, can it be merged? There's another issue I would like to move on to.
Thanks.
@leecalcote @Avi-88

**Comment by Avi-88** [comment]
Don't worry about it @sidtohan , your PR will get merged once the final approving review is done. It might take some time as there are many other PR's to go through as well. Just so you know , if any of your PR goes unnoticed for too long you can just ping it in slack or bring it up in the weekly dev call, thanks

**Comment by sidtohan** [comment]
I see. @Avi-88 thanks a lot for your guidance.

**Comment by Chadha93** [comment]
@sidtohan Good stuff here, just a minor to look the bottom border is getting cut here. Will you make a fix for this? 
image

**Comment by sidtohan** [comment]
Alright sure I'll look into this.

**Comment by sidtohan** [comment]
@Chadha93 I have fixed the issue. Kindly take a look whenever possible.
Thanks.

**Review by Chadha93 — APPROVED** [review]

**Pull request merged**
