### PR TITLE
feat: Add validation of preventing signing up from anonymous mail domains

### LINKED ISSUE #123: Prevent signup using anonymous mail domains
#### Current Behavior
Anyone can signup to use the Meshery Playground. Signup is necessary to ensure accountability given the open cluster nature of the playground.

#### Desired Behavior
Disallow signups from the following domains:

- @duck.com
- @anonaddy.me
- @protonmail.com
- @tuta.io

#### Implementation
Field validation using javascript and regex.

#### Acceptance Tests
1. Users who signup with any of the domains listed above are not allowed to submit the form.
1. Users who signup with any of the domains listed above are shown the following message:

"Use of the <matching-domain-name-here> is not allowed. Please use a non-anonymous email address / domain. 

The Meshery Playground is connected to live Kubernetes cluster(s) and allows users full-control over those clusters. Requiring users to register a non-anonymous user account keeps the Playground safe and healthy for all to enjoy. Without requiring users to sign-in, the Meshery Playground would allow anonymous access for anyone and everyone to potentially perform nefarious acts. Sign-up to receive a user account, entitled with perpetually free and full access the Playground environment."

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

### PR DESCRIPTION
**Pull request by codingmickey**
**Notes for Reviewers**

Blocking signing up from the following domains:
- duck.com
- anodady.me
- protonmail.com
- tuta.io

The list can be expanded in the future by just adding more domains in this regex

https://github.com/codingmickey/play/blob/e809dcefef7a10c3d3c7e93f473d78e0be3a310a/site/src/components/SignupForm/index.js#L19

This PR fixes #123 

If any changes are required do let me know!

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@codingmickey will you confirm that mutli-word first and last names, whether with whitespace or hyphenations is allowed?

**Comment by leecalcote** [comment]
I'm removing other reviewers, who have yet to offer feedback.

**Review by leecalcote — APPROVED** [review]
@codingmickey thanks for this. Will you please address the other concern regarding multi-word names?

Will you ensure that the layer5.io forms follow this same approach?

**Comment by leecalcote** [comment]
@codingmickey Build failure:

```
5:19:29 PM: src/components/SignupForm/index.js
5:19:29 PM:   Line 50:9:  'errorRole' is assigned a value but never used                                                                                                                                                                                   no-unused-vars
5:19:29 PM:   Line 66:6:  React Hook useEffect has a missing dependency: 'onSubmit'. Either include it or remove the dependency array. If 'onSubmit' changes too often, find the parent component that defines it and wrap that definition in useCallback  react-hooks/exhaustive-deps
```

**Comment by codingmickey** [comment]
> @codingmickey thanks for this. Will you please address the other concern regarding multi-word names?

Sure I can work upon that..
 
> Will you ensure that the layer5.io forms follow this same approach?

Aye aye

**Comment by codingmickey** [comment]
> @codingmickey Build failure:
> 
> ```
> 5:19:29 PM: src/components/SignupForm/index.js
> 5:19:29 PM:   Line 50:9:  'errorRole' is assigned a value but never used                                                                                                                                                                                   no-unused-vars
> 5:19:29 PM:   Line 66:6:  React Hook useEffect has a missing dependency: 'onSubmit'. Either include it or remove the dependency array. If 'onSubmit' changes too often, find the parent component that defines it and wrap that definition in useCallback  react-hooks/exhaustive-deps
> ```

Oops these didn't occur on my local, sorry about it.. will update and make a new pr

**Comment by leecalcote** [comment]
@codingmickey will you consider an update to support this special character issue in the registration forms? - ā

**Pull request merged**
