### PR TITLE
fix: add modified regex for the firstName and lastName

### PR DESCRIPTION
**Pull request by codingmickey**
**Notes for Reviewers**

This PR fixes https://github.com/meshery/play/pull/125#pullrequestreview-1533788423

Allows

- Multi-word names
- Names with -
- Special language characters like ā

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by codingmickey** [comment]
Expect a PR regarding the build failure too by today..

**Comment by leecalcote** [comment]
@saaagarsingh

**Review by Avi-88 — APPROVED** [review]
Sorry for the delay, this got lost in other notifications. I tested it with a bunch of different names with special characters and also with some multi word names and it handles the spaces correctly so LGTM good work @codingmickey :)

**Comment by Ghat0tkach** [comment]
Hey @codingmickey 
Let's discuss it on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)

https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Pull request closed without merging**
